[package]
name = "minigrep-cli-tool"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A simple cli tool to search upon a text file for lines containing specified string"

[dependencies]
